#!/usr/bin/env python3
# Copyright 2026 NXP
# SPDX-License-Identifier: Apache-2.0
"""Turn tflite-micro's micro_speech test WAVs into the clips this sample sends.

The clips are checked in because the sample must build without the optional
tflite-micro module present on the host; this script records where they came
from and how to regenerate them.

    ./make_test_clips.py <tflite-micro>/tensorflow/lite/micro/examples/micro_speech/testdata
"""
import pathlib
import struct
import sys
import wave

CLIPS = ("yes_1000ms", "no_1000ms")


def main(testdata: pathlib.Path, out: pathlib.Path) -> None:
    body = ['/* Generated by scripts/make_test_clips.py. Do not edit. */',
            '#include "test_clips.h"', '']
    decl = ['/* Generated by scripts/make_test_clips.py. Do not edit. */',
            '#ifndef TEST_CLIPS_H_', '#define TEST_CLIPS_H_', '',
            '#include <stdint.h>', '#include <stddef.h>', '']
    for name in CLIPS:
        with wave.open(str(testdata / f"{name}.wav"), "rb") as w:
            if w.getnchannels() != 1 or w.getsampwidth() != 2 or w.getframerate() != 16000:
                raise SystemExit(f"{name}: expected 16 kHz mono 16-bit")
            n = w.getnframes()
            samples = struct.unpack("<%dh" % n, w.readframes(n))
        var = name.replace("_1000ms", "") + "_clip"
        body.append(f"const int16_t {var}[{n}] = {{")
        for i in range(0, n, 16):
            body.append("\t" + ", ".join(str(v) for v in samples[i:i + 16]) + ",")
        body += ["};", f"const size_t {var}_len = {n};", ""]
        decl += [f"extern const int16_t {var}[];", f"extern const size_t {var}_len;"]
    decl += ['', '#endif /* TEST_CLIPS_H_ */']
    (out / "test_clips.c").write_text("\n".join(body) + "\n")
    (out / "test_clips.h").write_text("\n".join(decl) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(pathlib.Path(sys.argv[1]), pathlib.Path(__file__).resolve().parent.parent / "src")
